programs:
  nginx:
    command: "echo 'Nginx running' && sleep 10"
    numprocs: 10
    autostart: true # Manuel başlatacağız
    autorestart: never # Manuel durduracağız
    exitcodes: [0]
    startsecs: 5
    startretries: 3
    stopsignal: TERM
    stoptime: 10
    stdout: "/tmp/nginx.stdout"
    stderr: "/tmp/nginx.stderr"
    env:
      STARTED_BY: "taskmaster"
    workingdir: "/tmp"
    umask: 022

  test:
    command: "mkdiqerw test && echorqwe 'Test running' && sleep 5" 
    numprocs: 2
    autostart: true
    autorestart: never
    exitcodes: [0,1,2,126,127,128,130,255]
    startsecs: 10
    startretries: 5
    stopsignal: TERM
    stoptime: 10
    stdout: "/tmp/test.stdout"
    stderr: "/tmp/test.stderr"
    env:
      STARTED_BY: "taskmaster"
      TEST_MODE: "true"
    workingdir: "/Users/mukeles/Desktop/taskmaster"
    umask: 022
