programs:
  nginx:
    command: "echo 'Nginx running' && sleep 10"
    numprocs: 10
    autostart: true # Manuel başlatacağız
    autorestart: always
    exitcodes: [0]
    startsecs: 5
    startretries: 3
    stopsignal: TERM
    stoptime: 10
    stdout: "/tmp/nginx.stdout"
    stderr: "/tmp/nginx.stderr"
    env:
      STARTED_BY: "taskmaster"
    workingdir: "/tmp"
    umask: 022
  test:
    command: "echo 'Merhaba dunya' && sleep 10"
    numprocs: 10
    autostart: true
    autorestart: always
    exitcodes: [0]
    startsecs: 5
    startretries: 3
    stopsignal: TERM
    stoptime: 10

  test2:
    command: "echo 'Merhaba dunya' && sleep 10"
    numprocs: 10
    autostart: true
    autorestart: always
    exitcodes: [0]
    startsecs: 5
    startretries: 3
    stopsignal: TERM
    stoptime: 10
