programs:
  nginx:
    command: "echo 'Nginx running' && sleep 10"
    numprocs: 2
    autostart: true
    autorestart: unexpected
    exitcodes: [0]
    startsecs: 5
    startretries: 3
    stopsignal: TERM
    stoptime: 10
    stdout: "/tmp/nginx.stdout"
    stderr: "/tmp/nginx.stderr"
    env:
      STARTED_BY: "taskmaster"
    workingdir: "/tmp"
    umask: 022